# Generated by Django 4.2.29 on 2026-03-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Marka Adı')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='İkon (emoji veya CSS class)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Kategori Görseli')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Ürün Açıklaması')),
                ('specifications', models.TextField(blank=True, help_text='Her satır bir özellik. Örn: Renk: Beyaz', verbose_name='Teknik Özellikler')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ürün Görseli')),
                ('unit', models.CharField(default='Adet', max_length=50, verbose_name='Birim (Adet, Kova, Rulo, Paket vb.)')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, help_text='Birim başına ağırlık — ambar ücreti hesabında kullanılır', max_digits=8, verbose_name='Ağırlık (kg)')),
                ('width_cm', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Genişlik (cm)')),
                ('height_cm', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Yükseklik (cm)')),
                ('depth_cm', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Derinlik (cm)')),
                ('price_adet', models.DecimalField(decimal_places=2, help_text='Tüketiciye gösterilecek nihai birim fiyat', max_digits=10, verbose_name='Adet Fiyatı (KDV dahil, nakliye dahil)')),
                ('price_palet', models.DecimalField(blank=True, decimal_places=2, help_text='Boş bırakılırsa ürün palet olarak satılmaz', max_digits=10, null=True, verbose_name='Palet Birim Fiyatı (KDV hariç)')),
                ('price_tir', models.DecimalField(blank=True, decimal_places=2, help_text='Boş bırakılırsa ürün tır olarak satılmaz', max_digits=10, null=True, verbose_name='Tır Birim Fiyatı (KDV hariç)')),
                ('profit_margin_adet', models.DecimalField(decimal_places=2, default=0, help_text='Sadece admin referansı', max_digits=5, verbose_name='Adet Kâr Marjı (%)')),
                ('profit_margin_palet', models.DecimalField(decimal_places=2, default=0, help_text='Sadece admin referansı', max_digits=5, verbose_name='Palet Kâr Marjı (%)')),
                ('profit_margin_tir', models.DecimalField(decimal_places=2, default=0, help_text='Sadece admin referansı', max_digits=5, verbose_name='Tır Kâr Marjı (%)')),
                ('kdv_rate', models.PositiveIntegerField(default=20, verbose_name='KDV Oranı (%)')),
                ('min_order_adet', models.PositiveIntegerField(default=1, verbose_name='Minimum Adet Sipariş')),
                ('palet_quantity', models.PositiveIntegerField(default=0, help_text='0 ise palet satışı yok', verbose_name='Bir Paletteki Adet Sayısı')),
                ('tir_quantity', models.PositiveIntegerField(default=0, help_text='0 ise tır satışı yok', verbose_name='Bir Tırdaki Adet Sayısı')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Depo Stoğu')),
                ('is_factory_direct', models.BooleanField(default=False, verbose_name='Fabrikadan Direkt Sevk')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand', verbose_name='Marka')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['category', 'name'],
            },
        ),
    ]
