# Generated by Django 4.2.29 on 2026-03-23 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=200, verbose_name='Ad Soyad')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('guest_address', models.TextField(blank=True, verbose_name='Açık Adres')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Sipariş No')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('paid', 'Ödeme Alındı'), ('processing', 'Hazırlanıyor'), ('shipped', 'Sevk Edildi'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ara Toplam (TL)')),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Nakliye (TL)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Tutarı (TL)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Genel Toplam (TL)')),
                ('notes', models.TextField(blank=True, verbose_name='Sipariş Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address', verbose_name='Teslimat Adresi')),
                ('guest_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.city', verbose_name='İl')),
                ('guest_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.district', verbose_name='İlçe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_mode', models.CharField(choices=[('ADET', 'Adet'), ('PALET', 'Palet'), ('TIR', 'Tır')], default='ADET', max_length=10, verbose_name='Satış Modu')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat (TL)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nakliye Maliyeti (TL)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Sipariş')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
            },
        ),
    ]
