# Generated by Django 4.2.29 on 2026-03-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='İl Adı')),
                ('plate_code', models.CharField(max_length=2, unique=True, verbose_name='Plaka Kodu')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='Bölge')),
            ],
            options={
                'verbose_name': 'İl',
                'verbose_name_plural': 'İller',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(help_text='Örn: Aras Kargo, Horoz Lojistik', max_length=100, verbose_name='Lojistik Firma')),
                ('region', models.CharField(blank=True, help_text='Boş bırakılırsa tüm bölgelere uygulanır', max_length=50, verbose_name='Bölge')),
                ('calc_type', models.CharField(choices=[('per_kg', 'Kilogram Başına'), ('per_desi', 'Desi Başına'), ('per_unit', 'Birim Başına (sabit)')], default='per_kg', max_length=20, verbose_name='Hesaplama Tipi')),
                ('cost', models.DecimalField(decimal_places=2, help_text='kg başına, desi başına veya sabit — tipe göre', max_digits=10, verbose_name='Birim Maliyet (TL)')),
                ('min_charge', models.DecimalField(decimal_places=2, default=0, help_text='Hesaplanan tutar bunun altındaysa bu tutar uygulanır', max_digits=10, verbose_name='Minimum Ücret (TL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('city', models.ForeignKey(blank=True, help_text='Şehir bazlı tarife (öncelikli)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_tariffs', to='logistics.city', verbose_name='İl')),
            ],
            options={
                'verbose_name': 'Nakliye Tarifesi',
                'verbose_name_plural': 'Nakliye Tarifeleri',
                'ordering': ['provider_name', 'region'],
            },
        ),
        migrations.CreateModel(
            name='AmbarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='Bölge')),
                ('estimated_fee_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tahmini kg Başı Ambar Ücreti (TL)')),
                ('notes', models.TextField(blank=True, default='Kesin ücret sevkiyat günü belirlenir.', verbose_name='Not')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambar_configs', to='logistics.city', verbose_name='İl')),
            ],
            options={
                'verbose_name': 'Ambar Ayarı',
                'verbose_name_plural': 'Ambar Ayarları',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İlçe Adı')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='logistics.city', verbose_name='İl')),
            ],
            options={
                'verbose_name': 'İlçe',
                'verbose_name_plural': 'İlçeler',
                'ordering': ['name'],
                'unique_together': {('city', 'name')},
            },
        ),
    ]
