# Generated by Django 4.2.29 on 2026-03-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='POS Adı')),
                ('provider_type', models.CharField(choices=[('company', 'Şirket POS (Adet Siparişleri)'), ('factory', 'Fabrika POS (Toptan Siparişler)')], default='company', max_length=20, verbose_name='POS Tipi')),
                ('factory_name', models.CharField(blank=True, help_text='Fabrika POS ise fabrika adı', max_length=200, verbose_name='Fabrika Adı')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=500, verbose_name='API Secret')),
                ('merchant_id', models.CharField(blank=True, max_length=200, verbose_name='Merchant ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('max_installments', models.PositiveIntegerField(default=1, verbose_name='Maksimum Taksit Sayısı')),
                ('installment_rates', models.JSONField(blank=True, default=dict, help_text='{"2": 0, "3": 0, "6": 1.5, "9": 3.0, "12": 5.0}', verbose_name='Taksit Oranları')),
            ],
            options={
                'verbose_name': 'Sanal POS',
                'verbose_name_plural': "Sanal POS'lar",
            },
        ),
        migrations.CreateModel(
            name='POSRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_mode', models.CharField(choices=[('ADET', 'Adet Siparişleri'), ('TOPTAN', 'Toptan Siparişler (Palet + Tır)')], max_length=10, verbose_name='Satış Modu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Başlangıcı')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Bitişi')),
                ('notes', models.TextField(blank=True, help_text='Örn: Bu hafta A fabrikasına çekiliyor', verbose_name='Not')),
                ('pos_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='payments.posprovider', verbose_name='POS Sağlayıcı')),
            ],
            options={
                'verbose_name': 'POS Yönlendirme',
                'verbose_name_plural': 'POS Yönlendirmeleri',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (TL)')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='Taksit Sayısı')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('success', 'Başarılı'), ('failed', 'Başarısız'), ('refunded', 'İade Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='İşlem ID')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='POS Yanıt Verisi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order', verbose_name='Sipariş')),
                ('pos_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.posprovider', verbose_name='POS Sağlayıcı')),
            ],
            options={
                'verbose_name': 'Ödeme İşlemi',
                'verbose_name_plural': 'Ödeme İşlemleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
